import type { Metadata } from "next";
import Image from "next/image";
import { Compass, Handshake, Scales, Target } from "@phosphor-icons/react/dist/ssr";
import { SocialCulturalSection } from "@/components/social-cultural-section";
import { CtaBand } from "@/components/cta";
import { PageHero, SectionTitle } from "@/components/section";

export const metadata: Metadata = { title: "A empresa", description: "Conheça a Oliveira & Paim e sua abordagem integrada de assessoria empresarial." };

export default function EmpresaPage() {
  const values = [[Compass, "Clareza", "Traduzir cenários complexos em prioridades compreensíveis."], [Target, "Praticidade", "Conectar estratégia à rotina e às decisões que precisam acontecer."], [Scales, "Responsabilidade", "Atuar com critério técnico, ética e respeito ao contexto."], [Handshake, "Proximidade", "Construir soluções com diálogo, presença e acompanhamento."]];
  return <><PageHero className="company-hero" eyebrow="A Oliveira & Paim" title="Uma visão integrada para empresas mais organizadas e seguras." text="Unimos gestão, finanças, pessoas, compliance e assessoria jurídica para apoiar pequenos e médios empresários em decisões que exigem clareza." image="/images/hero-empresa-editorial.webp" imageAlt="Cena ilustrativa de planejamento e análise empresarial" />
  <section className="section"><div className="container split"><div><SectionTitle eyebrow="Nossa atuação" title="Estratégia personalizada, sem fórmulas prontas." text="Cada negócio possui um contexto próprio. Por isso, nosso trabalho começa pela compreensão da operação, das prioridades e das pessoas envolvidas." /><p className="large-copy">A partir dessa leitura, estruturamos soluções proporcionais ao momento da empresa e acompanhamos sua aplicação, conectando orientação técnica e execução.</p></div><div className="image-frame reveal"><Image src="/images/strategy-session.png" alt="Análise de indicadores e processos empresariais" fill sizes="(max-width: 800px) 100vw, 50vw" /></div></div></section>
  <section className="section section-soft"><div className="container"><SectionTitle eyebrow="Princípios" title="O que orienta nosso trabalho." center /><div className="values-grid">{values.map(([Icon, title, text]) => { const ValueIcon = Icon as typeof Compass; return <article key={String(title)}><ValueIcon size={34} weight="thin" /><h3>{String(title)}</h3><p>{String(text)}</p></article>; })}</div></div></section>
  <section className="section dark-section"><div className="container"><SectionTitle eyebrow="Especialistas" title="Conhecimento complementar a serviço da sua empresa." text="A Oliveira & Paim reúne competências em gestão, finanças, pessoas, compliance e direito empresarial." /><div className="team-grid"><article className="team-card reveal"><div className="team-photo"><Image src="/images/instagram/luis-executivo-centered.webp" alt="Luís Henrique Oliveira Paim" fill loading="eager" sizes="(max-width: 900px) 100vw, 50vw" /></div><div className="team-copy"><span>Diretor Executivo</span><h3>Luís Henrique Oliveira Paim</h3><p>Mais de 15 anos de experiência em gestão estratégica, consultoria empresarial e administração. MBA em Gestão Empresarial pela FGV e formação em Gestão de Recursos Humanos. Atua em planejamento, gestão financeira e operacional, liderança de equipes e desenvolvimento de negócios.</p></div></article><article className="team-card reveal"><div className="team-photo"><Image src="/images/instagram/eduardo-retrato.webp" alt="Eduardo Osmar de Oliveira" fill loading="eager" sizes="(max-width: 900px) 100vw, 50vw" /></div><div className="team-copy"><span>Diretor Jurídico</span><h3>Eduardo Osmar de Oliveira</h3><p>Advogado, OAB/DF nº 73.527, formado em Direito pela UCDB, com pós-graduações em contratos, compliance, direito digital e governança de dados. Atua em assessoria jurídica empresarial, elaboração e revisão de contratos, LGPD, prevenção de riscos e organização de processos.</p></div></article></div></div></section><SocialCulturalSection /><CtaBand /></>;
}
