import Image from "next/image";
import Link from "next/link";
import type { CSSProperties } from "react";
import { ArrowRight, CheckCircle, InstagramLogo } from "@phosphor-icons/react/dist/ssr";
import { CtaBand } from "@/components/cta";
import { serviceIcons } from "@/components/icons";
import { SectionTitle } from "@/components/section";
import { InstagramFeed } from "@/components/instagram-feed";
import { articles, services } from "@/lib/content";

export default function Home() {
  return <>
    <section className="hero"><Image src="/images/hero-socios.png" alt="Luis Henrique Paim e Eduardo Osmar de Oliveira em ambiente executivo" fill priority sizes="(max-width: 600px) 1px, 100vw" className="hero-image hero-founders hero-desktop-image" /><Image src="/images/hero-socios-mobile.png" alt="" fill priority sizes="(max-width: 600px) 100vw, 1px" className="hero-image hero-founders-mobile" /><div className="hero-overlay" /><div className="container hero-content"><span className="eyebrow">Assessoria empresarial estratégica</span><h1>Clareza para decidir.<br />Estrutura para crescer.</h1><p>Soluções personalizadas em gestão, financeiro, pessoas e compliance para empresas que querem avançar com segurança.</p><div className="hero-actions"><Link className="button button-gold" href="/diagnostico">Agendar diagnóstico</Link><Link className="text-link" href="/solucoes">Conhecer soluções <ArrowRight /></Link></div></div></section>
    <section className="service-strip"><div className="container strip-grid">{services.map((service) => { const Icon = serviceIcons[service.slug as keyof typeof serviceIcons]; return <Link href={`/solucoes/${service.slug}`} key={service.slug}><Icon size={34} weight="thin" /><span>{service.title}</span></Link>; })}</div></section>
    <section className="section"><div className="container split"><div><SectionTitle eyebrow="Diagnóstico que direciona" title="Organização começa por uma leitura clara do negócio." text="Conectamos estratégia e execução para que cada decisão tenha contexto, prioridade e acompanhamento." /><div className="check-list"><span><CheckCircle /> Abordagem personalizada</span><span><CheckCircle /> Visão integrada da empresa</span><span><CheckCircle /> Plano prático e proporcional</span></div><Link className="text-link dark" href="/empresa">Conheça nossa abordagem <ArrowRight /></Link></div><div className="image-frame reveal"><Image src="/images/strategy-session.png" alt="Profissionais analisando indicadores e processos empresariais" fill sizes="(max-width: 800px) 100vw, 50vw" /></div></div></section>
    <section className="section section-soft services-stage"><div className="service-orbit service-orbit-one" aria-hidden="true" /><div className="service-orbit service-orbit-two" aria-hidden="true" /><div className="container"><SectionTitle eyebrow="Soluções integradas" title="O suporte certo para cada etapa da sua empresa." text="Atuação técnica, linguagem acessível e acompanhamento próximo para organizar o presente e sustentar os próximos passos." center /><div className="cards-grid">{services.map((service, index) => { const Icon = serviceIcons[service.slug as keyof typeof serviceIcons]; return <article className="service-card reveal" style={{ "--reveal-delay": `${index * 70}ms` } as CSSProperties} key={service.slug}><span className="service-index">0{index + 1}</span><Icon size={36} weight="thin" /><span>{service.eyebrow}</span><h3>{service.title}</h3><p>{service.summary}</p><Link href={`/solucoes/${service.slug}`} aria-label={`Conhecer ${service.title}`}>Explorar solução <ArrowRight /></Link></article>; })}</div></div></section>
    <section className="section dark-section"><div className="container split"><div><SectionTitle eyebrow="Como atuamos" title="Método, proximidade e responsabilidade em cada decisão." text="Começamos pelo contexto real da empresa. A partir dele, definimos prioridades, implantamos soluções e acompanhamos a evolução." /></div><ol className="steps"><li><strong>01</strong><div><h3>Entender</h3><p>Escuta, diagnóstico e leitura integrada dos desafios.</p></div></li><li><strong>02</strong><div><h3>Estruturar</h3><p>Plano de ação com entregas, responsáveis e critérios claros.</p></div></li><li><strong>03</strong><div><h3>Acompanhar</h3><p>Rotina de análise para ajustar a direção e consolidar avanços.</p></div></li></ol></div></section>
    <section className="section"><div className="container"><div className="title-row"><SectionTitle eyebrow="Conteúdos" title="Informação para decisões mais maduras." /><Link className="text-link dark" href="/conteudos">Ver todos <ArrowRight /></Link></div><div className="articles-grid">{articles.slice(0,3).map((a) => <article className="article-card" key={a.slug}><span>{a.category} · {a.readTime}</span><h3>{a.title}</h3><p>{a.excerpt}</p><Link href={`/conteudos/${a.slug}`}>Ler artigo <ArrowRight /></Link></article>)}</div></div></section>
    <section className="section instagram-section"><div className="container"><div className="instagram-heading"><SectionTitle eyebrow="Presença digital" title="Conteúdo que aproxima gestão e decisão." text="Publicações reais da Oliveira & Paim sobre gestão, finanças, processos e segurança empresarial." /><a className="button instagram-button" href="https://www.instagram.com/oliveiraepaim/" target="_blank" rel="noreferrer"><InstagramLogo size={20} /> Seguir @oliveiraepaim</a></div><InstagramFeed /></div></section>
    <CtaBand />
  </>;
}
